swndpp/ndpp/applications/recepcion/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de la aplicacion
    url(
        r'^guia-registrar/$',
        views.GuideRegisterView.as_view(),
        name='add-guide'
    ),
    #url para listar guias
    url(
        r'^guia-lista/$',
        views.SearchGuideView.as_view(),
        name='list-guide'
    ),
    #url para listar diarios
    url(
        r'^magazine-listar/$',
        views.MagazineListView.as_view(),
        name='list-magazine'
    ),
    #url para agregar diarios
    url(
        r'^magazine-add/$',
        views.MagazineCreate.as_view(),
        name='add-magazine'
    ),
    #url para agregar productos
    url(
        r'^prod-add/$',
        views.ProductCreate.as_view(),
        name='add-prod'
    ),
    #url para listar diarios
    url(
        r'^lista-dias-diarios/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.DaysTemplateView.as_view(),
        name='list_day-magazine'
    ),
    url(
        r'^almacen/recepcion/producto/add/plantilla/(?P<pk>\d+)/$',
        views.ProductCreatePlantillaView.as_view(),
        name='magazine-prod_plantilla'
    ),
    url(
        r'^almacen/recepcion/Diario/day/list/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.DaysTemplateView.as_view(),
        name='magazine-list_day'
    ),
    url(
        r'^almacen/recepcion/Diario/update/(?P<day>\d+)/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.MagazineUpdateView.as_view(),
        name='magazine-update'
    ),
    url(
        r'^almacen/recepcion/Diario/update/(?P<pk>\d+)/(?P<tipo>\d+)/$',
        views.ProductUpdateView.as_view(),
        name='magazine-update-prod'
    ),
    url(
        r'^almacen/recepcion/Diario/delete/(?P<pk>\d+)/$',
        views.MagazineDeleteView.as_view(),
        name='magazine-delete'
    ),




    #rest de aplicacion recepcion
    url(r'^', include('applications.recepcion.url_services', namespace="recepcion_servis_url")),
]

swndpp/ndpp/applications/reportes/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de la aplicacion
    url(
        r'^buscar-guia/$',
        views.SearchGuide.as_view(),
        name='reporte-search_guide'
    ),
    #url para buscar factura por numero
    url(
        r'^buscar-factura/$',
        views.SearchVoucher.as_view(),
        name='reporte-search_voucher'
    ),
    # url para agregar factura
    url(
        r'^agregar-comprobante/$',
        views.VoucherCreateView.as_view(),
        name='add-voucher'
    ),
    # url para modificar factura
    url(
        r'^ver-factura/(?P<pk>\d+)/$',
        views.VoucherUpdateView.as_view(),
        name='update-voucher'
    ),
    #url para anular faactura
    url(
        r'^eliminar-comprobante/(?P<pk>\d+)/$',
        views.VoucherDeleteView.as_view(),
        name='delete-voucher'
    ),
    #agregar nota de credito de una factura
    url(
        r'^agregar-nota-credito/(?P<pk>\d+)/$',
        views.NotaCreditoCreateView.as_view(),
        name='add-nota_credito'
    ),
    #url para anular nota de credito
    url(
        r'^eliminar-nota-de-credito/(?P<pk>\d+)/$',
        views.NotaCreditoDeleteView.as_view(),
        name='delete-nota_credito'
    ),
    # url para ver facturas sin nota de credito
    url(
        r'^voucher/factura-sin-credito/$',
        views.FacturaSinCredito.as_view(),
        name='voucher_sin-credito'
    ),





    #rest de aplicacion reportes
    url(r'^', include('applications.reportes.url_services', namespace="reportes_servis_url")),
]

swndpp/ndpp/ndpp/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
#import debug_toolbar

urlpatterns = [
    #urls para usuario
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.miscelanea.urls', namespace="miscelanea_app")),
    url(r'^', include('applications.recepcion.urls', namespace="recepcion_app")),
    url(r'^', include('applications.caja.urls', namespace="caja_app")),
    url(r'^', include('applications.reportes.urls', namespace="reportes_app")),
    url(r'^', include('applications.administracion.urls', namespace="administracion_app")),

    url(r'^admin/', admin.site.urls),
]

swndpp/ndpp/applications/recepcion/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
import operator
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
    ListView,
    TemplateView,
    View,
)

from applications.reportes.forms import SearchGuideForm
from .models import (
    Magazine,
    MagazineDay,
    Guide,
    DetailGuide,
)

from .forms import (
    MagazineForm,
    ProductAddForm,
    MagazineUpdateForm,
)


class MagazineListView(TemplateView):
    """vista para listar producto o diario"""
    template_name = 'recepcion/magazine/list.html'


class MagazineCreate(CreateView):
    """vista para crear un diario"""
    form_class = MagazineForm
    success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/add.html'

    def form_valid(self, form):
        print '****************'
        #guardamos magazine y recuperaos objeto
        magazine = form.save(commit=False)
        magazine.user_created = self.request.user

        magazine.tipo = '0'
        magazine.afecto = True
        magazine.save()

        for dia in ['0','1','2','3','4','5']:
            magazine_dia1 = MagazineDay(
                magazine=magazine,
                day=dia,
                precio_tapa=form.cleaned_data['precio_tapa'],
                precio_guia=form.cleaned_data['precio_guia'],
                precio_venta=form.cleaned_data['precio_venta'],
                user_created=self.request.user,
            )
            magazine_dia1.save()

        #registro de producto dia-domingo
        magazine_dia2 = MagazineDay(
            magazine=magazine,
            day='6',
            precio_tapa=form.cleaned_data['precio_tapad'],
            precio_guia=form.cleaned_data['precio_guiad'],
            precio_venta=form.cleaned_data['precio_ventad'],
            user_created=self.request.user,
        )
        magazine_dia2.save()

        return super(MagazineCreate, self).form_valid(form)


class ProductCreate(CreateView):
    """vista para crear un prodcuto"""
    form_class = ProductAddForm
    success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/add_prod.html'

    def form_valid(self, form):
        #guardamos magazine y recuperaos objeto
        magazine = form.save(commit=False)
        magazine.user_created = self.request.user

        magazine.tipo = '1'
        magazine.save()

        #registro de produto lines-sabado
        magazine_dia1 = MagazineDay(
            magazine=magazine,
            day='7',
            precio_tapa=form.cleaned_data['precio_tapa'],
            precio_guia=form.cleaned_data['precio_guia'],
            precio_venta=form.cleaned_data['precio_venta'],
            user_created=self.request.user,
        )
        magazine_dia1.save()

        return super(ProductCreate, self).form_valid(form)


class DaysTemplateView(TemplateView):
    template_name = 'recepcion/magazine/days.html'

    def get_context_data(self, **kwargs):
        context = super(DaysTemplateView, self).get_context_data(**kwargs)
        lista_dias = {
            '0':'LUNES',
            '1':'MARTES',
            '2':'MIERCOLES',
            '3':'JUEVES',
            '4':'VIERNES',
            '5':'SABADO',
            '6':'DOMINGO',
        }
        days = sorted(lista_dias.items(), key=operator.itemgetter(0))
        context['days'] = days
        context['tipo'] = self.kwargs.get('tipo',0)
        context['pk'] = self.kwargs.get('pk',0)
        return context


class MagazineUpdateView(UpdateView):
    """vista para modificar un diario"""
    model = Magazine
    form_class = MagazineUpdateForm
    success_url = success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/update.html'

    def get_initial(self, **kwargs):
        pk_dia = self.kwargs.get('day',0)
        day_ls = MagazineDay.objects.get(
            magazine=self.get_object(),
            day=pk_dia,
        )

        # recuperamos el objeto equipo
        initial = super(MagazineUpdateView, self).get_initial()
        initial['precio_tapa'] = day_ls.precio_tapa
        initial['precio_guia'] = day_ls.precio_guia
        initial['precio_venta'] = day_ls.precio_venta
        return initial

    def get_context_data(self, **kwargs):
        context = super(MagazineUpdateView, self).get_context_data(**kwargs)
        pk_dia = self.kwargs.get('day',0)
        dias = ['LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO']
        context['day'] = dias[int(pk_dia)]
        context['tipo'] = self.kwargs.get('tipo',0)
        return context

    def form_valid(self, form):
        #recuperamos los nuevos valores de formulario
        precio_tapa = form.cleaned_data['precio_tapa']
        precio_guia = form.cleaned_data['precio_guia']
        precio_venta = form.cleaned_data['precio_venta']

        #recuperamos DAY Lunes a Sabado
        pk_dia = self.kwargs.get('day',0)
        day = MagazineDay.objects.get(
            magazine=self.get_object(),
            day=pk_dia,
        )
        #guardamos los nuevos datos
        day.precio_tapa = precio_tapa
        day.precio_guia = precio_guia
        day.precio_venta = precio_venta
        day.user_modified = self.request.user
        day.save()
        return super(MagazineUpdateView, self).form_valid(form)


class ProductUpdateView(UpdateView):
    """vista para modificar un produco"""
    model = Magazine
    form_class = ProductAddForm
    success_url = success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/add_prod.html'

    def get_initial(self):
        day_ls = MagazineDay.objects.get(
            magazine=self.get_object(),
            day='7',
        )

        # recuperamos datos del objeto Magazine_day
        initial = super(ProductUpdateView, self).get_initial()

        return initial

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['tipo'] = self.kwargs.get('tipo',0)
        return context

    def form_valid(self, form):
        magazine = form.save()
        #recuperamos los nuevos valores de formulario
        precio_tapa = form.cleaned_data['precio_tapa']
        precio_guia = form.cleaned_data['precio_guia']
        precio_venta = form.cleaned_data['precio_venta']

        #recuperamos DAY Lunes a Sabado
        day_ls = MagazineDay.objects.get(
            magazine=self.get_object(),
            day='7',
        )
        #guardamos los nuevos datos
        day_ls.precio_tapa = precio_tapa
        day_ls.precio_guia = precio_guia
        day_ls.precio_venta = precio_venta
        day_ls.user_modified = self.request.user
        day_ls.save()
        return super(ProductUpdateView, self).form_valid(form)


class ProductCreatePlantillaView(CreateView):
    """vista para crear un producto en base a una palantilla"""
    model = Magazine
    form_class = ProductAddForm
    success_url = success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/plantilla.html'

    def get_initial(self):
        pk_magazine = self.kwargs.get('pk',0)
        magazine = Magazine.objects.get(pk=pk_magazine)
        # recuperamos datos del objeto Magazine_day
        initial = super(ProductCreatePlantillaView, self).get_initial()

        initial['name'] = magazine.name
        initial['provider'] = magazine.provider
        initial['description'] = magazine.description
        initial['afecto'] = magazine.afecto

        return initial

    def get_context_data(self, **kwargs):
        context = super(ProductCreatePlantillaView, self).get_context_data(**kwargs)
        context['tipo'] = self.kwargs.get('tipo',0)
        pk_magazine = self.kwargs.get('pk',0)
        context['object'] = Magazine.objects.get(pk=pk_magazine)
        return context

    def form_valid(self, form):
        #creamos objeto magazine
        magazine = form.save(commit=False)
        magazine.user_created = self.request.user

        magazine.tipo = '1'
        magazine.save()

        #registro de produto lines-sabado
        magazine_dia1 = MagazineDay(
            magazine=magazine,
            day='7',
            precio_tapa=form.cleaned_data['precio_tapa'],
            precio_guia=form.cleaned_data['precio_guia'],
            precio_venta=form.cleaned_data['precio_venta'],
            user_created=self.request.user,
        )
        magazine_dia1.save()
        return super(ProductCreatePlantillaView, self).form_valid(form)


class MagazineDeleteView(DeleteView):
    """vista para anular un diario o producto"""
    model = Magazine
    success_url = reverse_lazy('recepcion_app:list-magazine')
    template_name = 'recepcion/magazine/delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.disable = True
        self.object.user_modified = self.request.user
        self.object.save()
        success_url = self.get_success_url()

        return HttpResponseRedirect(success_url)


class GuideRegisterView(TemplateView):
    """vista para registrar guias"""
    template_name = 'recepcion/guide/add.html'



class SearchGuideView(ListView):
    '''
        busqueda de guias
    '''
    context_object_name = 'guias'
    template_name = 'recepcion/guide/list.html'

    def get_context_data(self, **kwargs):
        context = super(SearchGuideView, self).get_context_data(**kwargs)
        context['form'] = SearchGuideForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("item", '')
        r = self.request.GET.get("date", '')

        print '****************'
        print q
        print r
        #recuperamos guias

swndpp/ndpp/templates/recepcion/guide/add.html
{% extends "recepcion/base_recepcion.html" %}

{% block title %}Registrar Guia{% endblock title %}

{% block content %}
  {% include "include/header.html" %}

  <!-- *************** REGISTRO DE GUIA **************** -->
  <div class="guide-main" ng-app="DppApp" ng-controller="GuideCtrl as self" ng-init="self.cagar_agentes()">
    <h1 class="guide-title">Registro de guia de remision</h1>
    <div class="guide-card">
      <div class="guide-data">
        <h2 class="guide-card__title">Datos de Guia</h2>
        <div class="guide-card__form grid-x grid-padding-x">
          <div class="small-12 medium-10 large-6 cell">
            <label>Destinatario
              <select ng-model="self.guide.addressee">
                <option value="0">DPP</option>
                <option value="1">MAX CARGO</option>
              </select>
            </label>
          </div>
          <div class="small-12 medium-10 large-6 cell">
            <label>Numero de guia:
              <input type="text" ng-model="self.guide.number" placeholder="Numero de guia">
            </label>
          </div>
          <div class="small-12 medium-10 large-6 cell">
            <label>Departamento
              <select ng-model="self.guide.departamento">
                <option ng-repeat="d in self.departamentos" value="{$d.pk$}">{$ d.name $}</option>
              </select>
            </label>
          </div>
          <div class="small-12 medium-10 large-6 cell">
            <label>Proveedor
              <select ng-model="self.guide.provider">
                <option ng-repeat="p in self.providers" value="{$p.pk$}">{$ p.name $}</option>
              </select>
            </label>
          </div>
          <div class="small-12 medium-10 large-6 cell">
            <label>Fecha de Recepcion
              <input type="date" ng-model="self.date">
            </label>
          </div>
          <div class="small-12 medium-10 large-6 cell">
            <label>Inicio de Cobranza
              <input type="date" ng-model="self.date_cobranza">
            </label>
          </div>
        </div>
      </div>
      <div class="guide-data">
        <h2 class="guide-card__title">Datos de Producto</h2>
        <div class="guide-card__form">
          <div ng-repeat="c in self.cantidad" class="grid-x grid-padding-x align-center">
            <div class="small-12 medium-3 large-2 cell">
              <input type="text" ng-model="self.buscar.item[c.id]" placeholder="Buscar...">
            </div>
            <div class="small-12 medium-4 large-4 cell">
              <select ng-model="self.prod.item[c.id]">
                <option ng-repeat="d in self.diarios | filter:self.buscar.item[c.id]" value="{$d.pk$}">
                  {$ d.magazine $}--{$ d.day $}
                </option>
              </select>
            </div>
            <div class="small-12 medium-2 large-2 cell">
              <input type="text" ng-model="self.count.item[c.id]" placeholder="Cantidad...">
            </div>
            <div class="small-12 medium-2 large-2 cell">
              <input type="text" ng-model="self.dev.item[c.id]" placeholder="Devo...">
            </div>
            <div class="small-10 medium-3 large-2 cell">
              <button type="button" class="success button" ng-click="self.addNewChoice()">+</button>
              <button type="button" class="button guide-main-btn__secondary" ng-click="self.removeChoice()">-</button>
            </div>
          </div>
        </div>
      </div>
      <div class="guide-data">
        <h2 class="guide-card__title">Datos de Entrega</h2>
        <div class="guide-card__form grid-x grid-padding-x align-center">
          <div class="small-12 medium-3 large-3 cell">
            <input type="text" ng-model="self.buscar_agente" placeholder="Buscar...">
          </div>
          <div class="small-12 medium-9 large-9 cell">
            <select ng-model="self.guide.agente">
              <option ng-repeat="a in self.agentes|filter:self.buscar_agente" value="{$a.pk$}">{$ a.name $}--{$ a.seudonimo $}</option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <p>{$ self.msj $}</p>
    <button class="button guide-main-btn__primary" ng-click="self.enviar()" ng-disabled="self.bloqueo">
      Guardar
    </button>
  </div>
{% endblock content %}

swndpp/ndpp/templates/recepcion/guide/list.html
{% extends "recepcion/base_recepcion.html" %}

{% block title %}Buscar Guia Registrada{% endblock title %}

{% block content %}
  {% include "include/header.html" %}
    <div class="callout">
      <form method="get">{% csrf_token %}
        <div class="grid-x grid-padding-x align-center align-bottom">
          <div class="small-12 medium-5 cell">
            <label>Numero de Guia:
              {{form.item}}
            </label>
          </div>
          <div class="small-12 medium-5 cell">
            <label>Fecha Registro
              {{form.date}}
            </label>
          </div>
          <div class="medium-2 cell">
            <input type="submit" class="button" value="Buscar">
          </div>
        </div>

      </form>
    </div>
    <div class="callout grid-x grid-padding-x align-center">
      <div class="small-12 medium-11 large-10 cell">
        <table class="stack">
          <thead>
            <tr>
              <th>Proveedor</th>
              <th>Nombre</th>
              <th>Numero guia</th>
              <th>Accion</th>
            </tr>
          </thead>
          <tbody>
            {% for g in items %}
              <tr>
                <td>{{g.guide.provider}}</td>
                <td>{{g.magazine_day.magazine.name}}</td>
                <td><strong>{{g.guide.number}}</strong></td>
                <td>
                  <a href="{% url 'reportes_app:add-voucher' g.guide.pk %}" class="button warning" title="agrega factura">+</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
{% endblock content %}