swndpp/ndpp/applications/administracion/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    #url para home de reporte
    url(
        r'^administracion/reportes/$',
        views.AdministracionReporte.as_view(),
        name='administracion-reporte_index'
    ),
    #url para lista de guias en reportes administracion
    url(
        r'^administracion/reportes/guia-lista/$',
        views.ListaGuiaReporte.as_view(),
        name='administracion-reporte_guia-lista'
    ),
    #url para lista de facturas - reporte control facturas
    url(
        r'^administracion/reportes/factura-lista/$',
        views.ListaFacturaReporte.as_view(),
        name='administracion-reporte_factura-lista'
    ),
    #url para liquidacion proveedor
    url(
        r'^administracion/reportes/liquidacion-proveedor/$',
        views.LiquidacionProveedorReporte.as_view(),
        name='administracion-reporte_liquidacion_proveedor'
    ),
    #url para liquidacion por facturra
    url(
        r'^administracion/reportes/liquidacion-proveedor-factura/$',
        views.LiquidacionFacturaProveedorReporte.as_view(),
        name='administracion-reporte_liquidacion_proveedor_factura'
    ),
    #url para agregar pagos de facturas
    url(
        r'^administracion/procesos/registra-pago-factura/$',
        views.LiquidacionRegistrarPagoReporte.as_view(),
        name='administracion-proceso_pagos_factura'
    ),
    #url para ver seguimiento de agentes
    url(
        r'^administracion/reporte/seguimiento-agentes/$',
        views.SeguimientoAgentesView.as_view(),
        name='administracion-seguimiento_agentes'
    ),
    #url para ver deudas de agente
    url(
        r'^administracion/reporte/deuda-agente/(?P<codigo>[-\w]+)/$',
        views.DeudaByAgentesView.as_view(),
        name='administracion-deuda_agentes'
    ),

    #url para emitir boleta de pago
    url(
        r'^administracion/procesos/emitir-boleta/$',
        views.EmitirBoletaView.as_view(),
        name='administracion-emitir_boleta'
    ),
    #url para reporte de ventas por fecha
    url(
        r'^administracion/reportes/ventas/por-fecha/$',
        views.CuadreVentasView.as_view(),
        name='administracion-ventas_por_fecha'
    ),
    #
    url(
        r'^administracion/reportes/faltantes/$',
        views.MontosFaltantesView.as_view(),
        name='administracion-reporte_faltantes'
    ),
    #
    url(
        r'^administracion/procesos/boletas-emitidas/$',
        views.ListaBoletasEmitidas.as_view(),
        name='administracion-proceso_boletas_emitidas'
    ),
    #
    url(
        r'^administracion/procesos/boleta-eliminar/(?P<pk>\d+)/$',
        views.DeleteBoletasEmitida.as_view(),
        name='administracion-proceso_boletas_eliminar'
    ),
    #url para pantalla buscar guias
    url(
        r'^administracion/reportes/buscar/$',
        views.SearchGuidesView.as_view(),
        name='administracion-reporte_buscar-guia'
    ),
    #url para ver el historial de una guia
    url(
        r'^administracion/reportes/history/(?P<pk>\d+)/$',
        views.HistoryGuidesView.as_view(),
        name='administracion-reporte_history-guia'
    ),


    #rest de aplicacion adminisracion
    url(r'^', include('applications.administracion.url_services', namespace="adminisracion_servis_url")),
]

swndpp/ndpp/ndpp/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
#import debug_toolbar

urlpatterns = [
    #urls para usuario
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.miscelanea.urls', namespace="miscelanea_app")),
    url(r'^', include('applications.recepcion.urls', namespace="recepcion_app")),
    url(r'^', include('applications.caja.urls', namespace="caja_app")),
    url(r'^', include('applications.reportes.urls', namespace="reportes_app")),
    url(r'^', include('applications.administracion.urls', namespace="administracion_app")),

    url(r'^admin/', admin.site.urls),
]

swndpp/ndpp/applications/administracion/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from model_utils.models import TimeStampedModel

from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings
from django.db import models

#app recepcion
from applications.recepcion.models import DetailGuide
#
from applications.reportes.models import Voucher


@python_2_unicode_compatible
class PaymentVoucher(TimeStampedModel):
    """Pagos de Factura"""

    RESPONSABILITY_CHOICES = (
        ('0','---'),
        ('1','Admin'),
        ('2','Almacen'),
        ('3','Caja'),
        ('4','Otros'),
    )

    factura = models.ForeignKey(
        Voucher,
        related_name="factura_pago",
    )
    codigo_pago = models.CharField(
        'Codigo de Transaccion',
        max_length=30,
    )
    date_pago = models.DateField(
        'fecha de pago',
        blank=True,
        null=True
    )
    responsabilidad = models.CharField(
        'Responsabilidad',
        max_length=2,
        choices=RESPONSABILITY_CHOICES
    )
    monto_real = models.DecimalField('monto real',max_digits=10, decimal_places=3)
    monto_factura = models.DecimalField('monto Factura',max_digits=10, decimal_places=3)
    diferencia = models.BooleanField(default=False)
    #saldado = models.BooleanField(default=True)
    user_created = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="voucher_pago_created",
        #editable=False
    )
    user_modified = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="voucher_pago_modified",
        blank=True,
        null=True,
        editable=False
    )

    class Meta:
        verbose_name = 'Pago de Facturas'
        verbose_name_plural = 'Pagos de Facturas'
        ordering = ['-created']

    def __str__(self):
        return str(self.factura.number)


@python_2_unicode_compatible
class Boleta(TimeStampedModel):
    """almacena boletas emitidas"""
    RS_CHOICES = (
        ('0','DPP'),
        ('1','MAX CARGO'),
    )

    number = models.CharField(
        blank=True,
        max_length=20
    )
    client = models.CharField(
        blank=True,
        max_length=200
    )
    date_emition = models.DateField(
        blank=True,
        null=True,
    )
    date_venta = models.DateField(
        blank=True,
        null=True,
    )
    razon_social = models.CharField(
        max_length=2,
        choices=RS_CHOICES
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=3
    )
    igv = models.DecimalField(
        max_digits=10,
        decimal_places=3
    )
    afecto = models.BooleanField(default=True)
    user_created = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="boleta_created",
        #editable=False
    )
    user_modified = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="boleta_modified",
        blank=True,
        null=True,
        editable=False
    )
    anulate = models.BooleanField(default=False)

    #objects = BoletaManager()

    def __str__(self):
        return str(self.number)


@python_2_unicode_compatible
class DetailBoleta(TimeStampedModel):
    """almacena boletas emitidas"""
    boleta = models.ForeignKey(Boleta)
    detail_guide = models.ForeignKey(DetailGuide)
    count = models.PositiveIntegerField(
        blank=True,
        null=True
    )
    precio_venta = models.DecimalField(
        max_digits=10,
        decimal_places=3
    )
    precio_sunat = models.DecimalField(
        max_digits=10,
        decimal_places=3
    )
    user_created = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="detailboleta_created",
        #editable=False
    )
    user_modified = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="detailboleta_modified",
        blank=True,
        null=True,
        editable=False
    )
    anulate = models.BooleanField(default=False)

    #objects = DetailBoletaManager()


    def __str__(self):
        return str(self.boleta.number)

swndpp/ndpp/applications/administracion/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
import operator
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
    ListView,
    TemplateView,
    View,
)

#app miscelanea
from applications.miscelanea.models import Vendor
#app recepcion
from applications.recepcion.models import DetailGuide, Guide

#app Caja
from applications.caja.models import Payment
#
from applications.caja.functions import (
    deuda_magazine_agente,
    deuda_magazine_agente_total,
    deuda_magazine_agente_detalle
)

#aplicacion reporte
from applications.reportes.models import Voucher, NotaCredito

#formulario
from .forms import (
    FilterForm,
    FilterProviderLiquidacion,
    ProviderLiquidacionForm,
    BoletaFilterForm,
    SearchGuidesForm
)

#
from .models import Boleta, DetailBoleta

#funciones
from .functions import (
    movimientos_by_guia_by_departamento,
    movimientos_by_guia_by_departamento_facturado,
    history_guide,
)

class AdministracionReporte(TemplateView):
    template_name = 'administracion/reportes/index.html'


class ListaGuiaReporte(ListView):
    """ lista guias modulo reportes """
    context_object_name = 'guias'
    template_name = 'administracion/reportes/guia/list.html'

    def get_context_data(self, **kwargs):
        context = super(ListaGuiaReporte, self).get_context_data(**kwargs)
        context['form'] = FilterForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("date_start", '')
        r = self.request.GET.get("date_end", '')
        s = self.request.GET.get("number", '')
        t = self.request.GET.get("state", '')
        queryset = DetailGuide.objects.filter_guide(q,r,s,t)
        return queryset


class ListaFacturaReporte(ListView):
    """ lista guias modulo reportes """
    context_object_name = 'consulta'
    template_name = 'administracion/reportes/factura/facturas.html'

    def get_context_data(self, **kwargs):
        context = super(ListaFacturaReporte, self).get_context_data(**kwargs)
        context['form'] = FilterForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("date_start", '')
        r = self.request.GET.get("date_end", '')
        s = self.request.GET.get("number", '')
        t = self.request.GET.get("state", '')
        facturas = Voucher.objects.filter_factura(q,r,s,t)
        notas = NotaCredito.objects.filter_nota(q,r)
        #devolvemos diccionario de facturas y notas de credito
        return {'facturas':facturas,'notas':notas}


class LiquidacionProveedorReporte(TemplateView):
    """ lista los movimiento de una guia desde su llegada compra total"""

    template_name = 'administracion/reportes/ventas/list.html'


class LiquidacionFacturaProveedorReporte(TemplateView):
    """ lista los movimiento de una factura"""

    template_name = 'administracion/reportes/ventas/lista_factura.html'
    #     queryset = movimientos_by_guia_by_departamento_facturado(q,r,s,t)
    #     return {'consulta':queryset[0],'total':queryset[1]}


class LiquidacionRegistrarPagoReporte(TemplateView):
    template_name = 'administracion/procesos/pagar_facturas.html'


class SeguimientoAgentesView(ListView):
    """ seguimiento de deudas de un agente"""

    context_object_name = 'agentes'
    template_name = 'administracion/reportes/agentes/list.html'

    def get_queryset(self):
        #recuperamos la consulta de agentes
        return Payment.objects.seguimiento_agentes()


class DeudaByAgentesView(ListView):
    """ Detalle deuda de un agente """

    context_object_name = 'diarios'
    template_name = 'administracion/reportes/agentes/deudas.html'

    def get_context_data(self, **kwargs):
        context = super(DeudaByAgentesView, self).get_context_data(**kwargs)
        context['deuda_total'] = deuda_magazine_agente_total(self.kwargs.get('codigo',0))
        context['agente'] = Vendor.objects.get(cod=self.kwargs.get('codigo',0))
        return context

    def get_queryset(self):
        #recuperamo codigo
        codigo=self.kwargs.get('codigo',0)
        #recuperamos la consulta de agentes
        return deuda_magazine_agente_detalle(codigo)


class EmitirBoletaView(TemplateView):
    """  vista para emitir comprobante de pago """
    template_name = 'administracion/procesos/emitir_boleta.html'


class ListaBoletasEmitidas(ListView):
    """ lista las boletas ya emitidas """
    context_object_name = 'boletas'
    template_name = 'administracion/procesos/lista_boletas.html'

    def get_context_data(self, **kwargs):
        context = super(ListaBoletasEmitidas, self).get_context_data(**kwargs)
        context['form'] = BoletaFilterForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("date_emition", '')
        if q:
            queryset = Boleta.objects.filter(
                date_emition=q,
                anulate=False,
            )
        else:
            queryset = []
        return queryset


class DeleteBoletasEmitida(DeleteView):
    """vista para anular una boleta emitida"""
    model = Boleta
    success_url = reverse_lazy('administracion_app:administracion-proceso_boletas_emitidas')
    template_name = 'administracion/procesos/delete_boleta.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.anulate = True
        self.object.user_modified = self.request.user
        self.object.save()
        #lista de boletas detalle
        detalle_boletas = DetailBoleta.objects.filter(
            boleta__pk=self.object.pk,
        )
        # anulamos cada boleta
        for db in detalle_boletas:
            db.anulate = True
            db.save()
            print 'Detalle boleta anulado'
        #
        success_url = self.get_success_url()

        return HttpResponseRedirect(success_url)


class SearchGuidesView(ListView):
    """ lista guias buscadas por numero de guia"""
    context_object_name = 'guias'
    template_name = 'administracion/reportes/guia/search.html'

    def get_context_data(self, **kwargs):
        context = super(SearchGuidesView, self).get_context_data(**kwargs)
        context['form'] = SearchGuidesForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("kword", '')
        if q:
            queryset = Guide.objects.filter(
                number__icontains=q,
                anulate=False,
            )
        else:
            queryset = Guide.objects.filter(
                anulate=False,
            )[:20]
        return queryset


class HistoryGuidesView(DetailView):
    model = Guide
    template_name = 'administracion/reportes/guia/history.html'

    def get_context_data(self, **kwargs):
        context = super(HistoryGuidesView, self).get_context_data(**kwargs)
        context['historial'] = history_guide(self.get_object().pk)
        return context

class CuadreVentasView(TemplateView):
    template_name = 'administracion/reportes/ventas/por_fecha.html'


class MontosFaltantesView(TemplateView):
    template_name = 'administracion/reportes/faltante/index.html'

swndpp/ndpp/templates/administracion/procesos/delete_boleta.html
{% extends "administracion/base_admin.html" %}

{% block title %}Eliminar Boleta {% endblock title %}

{% block content %}
  {% include "include/header.html" %}
  <div class="callout">
    <form action="{% url 'administracion_app:administracion-proceso_boletas_eliminar' boleta.pk %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="card">
          <div class="card-divider">
            Eliminar Boleta
          </div>
          <div class="card-section">
            <h4>¿Esta seguro de Eliminar Boleta: {{boleta.number}}?.</h4>
            <p>
              <button type="submit" class="button alert">Eliminar</button>
              <a href="{% url 'administracion_app:administracion-proceso_boletas_emitidas' %}" class="button secondary">Cancel</a>
            </p>
          </div>
        </div>
    </form>
  </div>
{% endblock content %}

swndpp/ndpp/templates/administracion/procesos/emitir_boleta.html
{% extends "administracion/base_admin.html" %}

{% block title %}Reporte Control de Facturas{% endblock title %}

{% block content %}
  {% include "include/header.html" %}

  <div class="grid-container" ng-app="DppApp" ng-controller="EmitirBoletaCtrl as self">
    <h5>Emitir Comprobante de pago:</h5>
    <div class="grid-x grid-margin-x align-center">
      <div class="cell small-12 medium-6 large-4">
        <label>Razon Social:
          <select ng-model="self.rs">
            <option value="0">DPP</option>
            <option value="1">MAX</option>
          </select>
        </label>
      </div>
      <div class="cell small-12 medium-6 large-4">
        <label>Seleccione Agente:
          <select ng-model="self.departamento">
            <option ng-repeat="d in self.departamentos" value="{$ d.pk $}">{$ d.name $}</option>
          </select>
        </label>
      </div>

      <div class="cell small-12 medium-6 large-4">
        <label>Fecha Venta:
          <input type="date" name="fecha" ng-model="self.fecha" ng-change="self.cargar_magazine()">
        </label>
      </div>

      <div class="cell small-12 medium-6 large-4">
        <label>Numero:
          <input type="text" name="numero boleta" placeholder="0002-21" ng-model="self.numero">
        </label>
      </div>
      <div class="cell small-12 medium-6 large-4">
        <label>Fecha Emision Boleta:
          <input type="date" name="facha boleta" ng-model="self.fecha_boleta">
        </label>
      </div>
      <div class="cell small-12 medium-6 large-4">
        <label>Aplicar Descuento de:
          <input type="text" name="facha boleta" placeholder="0.001" ng-model="self.descuento" ng-change="self.aplicar_descuento()">
        </label>
      </div>
      <div class="cell small-12 medium-6 large-12">
        <div class="grid-x">
          <div class="cell large-2">
            <label>Afectos:
              <input type="checkbox" name="afectos" ng-model="self.afecto">
            </label>
          </div>
        </div>
      </div>
    </div>
    <div class="grid-x align-center">
      <div class="cell small-12 large-3">
        <a href="{% url 'administracion_app:administracion-proceso_boletas_emitidas' %}" class="button primary">Todas las Boletas</a>
      </div>
      <div class="cell small-12 large-3">
        <button type="button" name="button" class="button secondary" ng-click="self.seleccionar_bloque()">Seleccionar Bloque</button>
      </div>
      <div class="cell small-12 large-3">
        <button type="button" name="button" class="button alert" ng-click="self.limpiar_bloque()">Limpiar Bloque</button>
      </div>
      <div class="cell small-12 large-3">
        <h3>Monto: S/. {$ self.total  $}</h3>
      </div>
    </div>
    <div class="grid-x align-center" style="margin-top:2em;">
      <table>
        <thead>
          <th>Codigo</th>
          <th>Diario</th>
          <th>Cantidad</th>
          <th>Precio U</th>
          <th>Total</th>
          <th>Estado</th>
          <th>Accion</th>
        </thead>
        <tbody>
          <tr ng-repeat="i in self.items |filter:{afecto:self.afecto}">
              <td>{$ i.codigo $}</td>
              <td>{$ i.magazine $}</td>
              <td><strong>{$ i.count $}</strong></td>
              <td><strong>{$ i.precio_sunat $}</strong></td>
              <td>{$ i.amount $}</td>
              <td>
                <span class="text-danger">Nuevo</span>
              </td>
              <td>
                <input type='checkbox' ng-model="i.emitido" ng-change="self.calcular_montos()">
              </td>
          </tr>
          <tr>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>
          <tr ng-repeat="ib in self.items_impreso |filter:{afecto:self.afecto}">
              <td>{$ ib.codigo $}</td>
              <td>{$ ib.magazine $}</td>
              <td><strong>{$ ib.count $}</strong></td>
              <td><strong>{$ ib.precio_sunat $}</strong></td>
              <td>{$ ib.amount $}</td>
              <td>
                <span style="color:red">Generado</span>
              </td>
              <td></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="grid-x grid-margin-x align-center">
      <div class="cell shrink">
        <button type="button" class="button warning" name="button" ng-click="self.generar_boleta()">Generar</button>
      </div>
    </div>
    <div class="grid-x align-center">
      <div class="cell callout">
        <table id="lista-facturas">
        <tbody>
            <td>
              <table class="table">
                <thead>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td></td>
                    <td>{$ self.numero $}</td>
                  </tr>
                  <tr></tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td colspan="3">SINDICATO DE VENDEDORES DE DIARIOS {$ self.departamento.boleta $}</td>
                    <td></td>
                    <td></td>
                    <td>{$ self.fecha_boleta_gen $}</td>
                  </tr>
                  <tr>
                  </tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>{$ self.departamento_boleta $}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                  </tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                </thead>
                <tbody>
                  <tr ng-repeat="i in self.items_selccionados">
                    <td></td>
                    <td>{$ i.codigo $}</td>
                    <td></td>
                    <td colspan="3">{$ i.magazine $}</td>
                    <td><strong>{$ i.count $}</strong></td>
                    <td><strong>{$ i.precio_sunat $}</strong></td>
                    <td>{$ i.amount $}</td>
                  </tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr></tr>
                  <tr>
                    <td></td>
                    <td colspan="8">{$ self.total_letra $}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                  </tr>
                  <tr></tr>
                  <tr></tr>
                  <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><strong>{$ self.total| currency: "S/." $}</strong></td>
                  </tr>
                </tbody>
              </table>
            </td>
        </tbody>
      </table>
      </div>
      <div class="cell shrink">
        <button type="button" id="imprimir" class="button secondary" onclick="imprimir_liquidacion('Comprobante-pago.xls')" ng-click="self.guardar_boleta()">Imprimir</button>
      </div>
    </div>
  </div>
{% endblock content %}

swndpp/ndpp/templates/administracion/procesos/lista_boletas.html
{% extends "administracion/base_admin.html" %}

{% block title %}Lista de Boletas{% endblock title %}

{% block content %}
  {% include "include/header.html" %}
  <div class="grid-container grid-container-padded">
    <form class="grid-x grid-margin-x aling-center callout" method="get">{% csrf_token %}
      <h2 class="cell">Buscar Boletas ya emitidas</h2>
      <div class="cell small-12 large-6">
        <div class="input-group">
          <span class="input-group-label"><i class="fa fa-calendar-o" aria-hidden="true"></i></span>
          {{form.date_emition}}
          <div class="input-group-button">
            <input type="submit" class="button" value="Buscar">
          </div>
        </div>
      </div>
    </form>

    <div class="grid-x">
      <table class="stack">
        <thead>
          <th>Razon Social</th>
          <th>Numero</th>
          <th>Agente</th>
          <th>Fecha Emsion</th>
          <th>Fecha Venta</th>
          <th>Monto</th>
          <th>Accion</th>
        </thead>
        <tbody>
          {% for b in boletas %}
            <tr>
              <td>
                {{b.get_razon_social_display}}
              </td>
              <td>
                {{b.number}}
              </td>
              <td>
                {{b.client}}
              </td>
              <td>
                {{b.date_emition}}
              </td>
              <td>
                {{b.date_venta}}
              </td>
              <td>
                {{b.amount}}
              </td>
              <td>
                <a href="{% url 'administracion_app:administracion-proceso_boletas_eliminar' b.pk %}" class="button alert">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock content %}

swndpp/ndpp/templates/administracion/procesos/pagar_facturas.html
{% extends "administracion/base_admin.html" %}

{% block title %}Reporte Control de Facturas{% endblock title %}

{% block content %}
  {% include "include/header.html" %}

  <div class="grid-x grid-margin-x align-center">
    <div class="cell shrink">
      <a href="{% url 'administracion_app:administracion-reporte_liquidacion_proveedor' %}" class="button secondary">Compra Total</a>
    </div>
    <div class="cell shrink">
      <a href="{% url 'administracion_app:administracion-reporte_liquidacion_proveedor_factura' %}" class="button success">Compra Facturada</a>
    </div>
    <div class="cell shrink">
      <a href="{% url 'administracion_app:administracion-proceso_pagos_factura' %}" class="button warning">Pagar Facturas</a>
    </div>
  </div>

  <h3 style="text-align:center"> Registra Pago de Facturas</h3>
  <div class="grid-container" ng-app="DppApp" ng-controller="FacturaCtrl as self" ng-init="self.listar_factura()">
    <div class="grid-x align-center">
      <div class="cell small-12 medium-6 large-4">
        <label>Filtrar por:
          <input type="text" ng-model="self.buscar" placeholder="Buscar...">
        </label>
      </div>
      <div class="cell small-12">
        <table>
          <thead>
            <tr>
              <th>Seleccion</th>
              <th>CODIGO</th>
              <th>FACTURA</th>
              <th>FECHA-EMISION</th>
              <th>MONTO FACT.</th>
              <th>M. NotaCredito</th>
              <th>M. Pagar</th>
              <th>Responsabilidad</th>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="f in self.facturas | filter:self.buscar" style="color:#C62828;" ng-style="f.correcto && {'color':'#212121'}">
              <td><input type='checkbox' ng-model="f.state" ng-click="self.recalcular_monto()"></td>
              <td>{$ f.number_interno $}</td>
              <td>{$ f.number $}</td>
              <td>{$ f.date_emition $}</td>
              <td style="font-size:1.3em;"><strong>{$ f.amount $}</strong></td>
              <td>{$ f.amount_nota $}</td>
              <td><input type='text' ng-model="f.monto_factura" value="f.monto_factura" ng-change="self.recalcular_monto()"></td>
              <td>
                <select ng-model="f.responsabilidad">
                  <option value="0">---</option>
                  <option value="1">Administracion</option>
                  <option value="2">Almacen</option>
                  <option value="3">Caja</option>
                  <option value="4">Otros</option>
                </select>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="cell small-12 large-12">
        <div class="grid-x grid-margin-x align-center callout">
          <div class="cell small-12 large-4">
            <h5><span style="text-align:center;">Monto Total Factura:</span> S/. {$ self.monto_total $}</h5>
            <h5><span style="text-align:center;">Monto Total Pagar:</span> S/. {$ self.monto_real $}</h5>
          </div>
          <div class="cell small-12 large-3">
            <input type="text" ng-model="self.codigo_pago" placeholder="codigo de pago">
          </div>
          <div class="cell small-12 large-3">
            <input type="date" ng-model="self.date_pago">
          </div>
          <div class="shrink">
            <button type="button" class="button" name="button" ng-click="self.registrar_pago()">Registrar Pago</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}