swnpuerto/nmagazine/applications/caja/pagos/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from . import views, viewsets
from .viewsets import MovimientosViewSet, PagoscreateViewSet

urlpatterns = [
    #urls para servicios
    url(
        r'^api/pagos/movimientos/(?P<pk>[-\w]+)/$',
        viewsets.MovimientosViewSet.as_view({'get': 'list'}),
        name='pagos-movimientos'
    ),
    url(
        r'^api/pagos/save/(?P<pk>[-\w]+)/$',
        viewsets.PagoscreateViewSet.as_view({'post': 'create'}),
        name='pagos-add'
    ),
    url(
        r'^api/ventas/save/$',
        viewsets.VentacreateViewSet.as_view({'post': 'create'}),
        name='pagos-venta_add'
    ),
    url(
        r'^api/pagos/ca1ja/cudrar/liquidacion/$',
        viewsets.CuadrarCajaViewSet.as_view({'get': 'list'}),
        name='pagos-reporte_liquidacion'
    ),
    url(
        r'^api/pagos/lista-productos-venta/$',
        viewsets.ProdVentaViewSet.as_view({'get': 'list'}),
        name='pagos-prod_venta'
    ),
    #urls para caja
    url(
        r'^caja/cobros/cobrar/cobros$',
        views.CobrosView.as_view(),
        name='pagos-cobrar'
    ),
    url(
        r'^caja/cobros/cobrar/anular/(?P<pk>\d+)/$',
        views.PaymentDeleteView.as_view(),
        name='pagos-anular'
    ),
    #urls para cuadrar caja
    url(
        r'^caja/cobros/cuadrar/caja/$',
        views.CuadrarCajaView.as_view(),
        name='pagos-cudarar'
    ),
    url(
        r'^caja/cobros/cobrar/cuadrar/detalle/(?P<pk>\d+)/$',
        views.DetalleCuadrarView.as_view(),
        name='pagos-detalle-cuadrar'
    ),
    url(
        r'^caja/cobros/cuadrar/confirmar/$',
        views.ConfirmarView.as_view(),
        name='pagos-confirmar'
    ),
    url(
        r'^caja/ventas/list/$',
        views.VentasListView.as_view(),
        name='venta-list'
    ),
    url(
        r'^caja/ventas/delete/(?P<pk>\d+)/$',
        views.VentaDeleteView.as_view(),
        name='venta-delete'
    ),
    #urls para cuadrar devoluciones
    url(
        r'^caja/cobros/reportes/devolucion$',
        views.DevolucionListView.as_view(),
        name='pagos-devoluciones'
    ),
    url(
        r'^caja/cobros/cobrar/devolucion/detalle/(?P<pk>\d+)/$',
        views.DetalleDevolucion.as_view(),
        name='pagos-detalle-devolucion'
    ),
    #urls para reportes
    url(
        r'^caja/cobros/reportes/deudores$',
        views.FaltantesView.as_view(),
        name='pagos-faltantes'
    ),
    url(
        r'^caja/cobros/reportes/anulados$',
        views.InvoceAnulados.as_view(),
        name='pagos-anulados'
    ),
    url(
        r'^caja/cobros/reportes/anulado/detalle/(?P<pk>\d+)/$',
        views.DetalleAnulado.as_view(),
        name='pagos-anulado-detalle'
    ),
    url(
        r'^caja/cobros/cuadrar/reporte/$',
        views.CuadrarReporteView.as_view(),
        name='pagos-cuadrar_reporte'
    ),
    url(
        r'^caja/cobros/reporte/devoluciones$',
        views.DevolucionReporteView.as_view(),
        name='pagos-devolucion_reporte'
    ),
    url(
        r'^caja/cobros/venta-tienda/$',
        views.VentaTiendaView.as_view(),
        name='pagos-tienda'
    ),
    url(
        r'^caja/reportes/guias-pendientes/$',
        views.GuiasPendientesListView.as_view(),
        name='guias-pendientes'
    ),
    url(
        r'^caja/reportes/guias-pendientes/deuda/(?P<pk>\d+)/$',
        views.DetalleGuiasPendientesListView.as_view(),
        name='guias-pendientes-detalle'
    ),

]

swnpuerto/nmagazine/applications/reportes/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from . import views, viewsets

urlpatterns = [
    #urls para servicios
    url(
        r'^api/ventas/cierre/$',
        viewsets.CierreMesViewSet.as_view({'get': 'list'}),
        name='api-cierre'
    ),
    url(
        r'^api/ventas/cierre/venta-neta/$',
        viewsets.VentanetaViewSet.as_view({'get': 'list'}),
        name='api-venta_neta'
    ),
    url(
        r'^api/ventas/cierre/ingreso-neto/$',
        viewsets.IngresonetoViewSet.as_view({'get': 'list'}),
        name='api-ingreso-neto'
    ),
    url(
        r'^api/reportes/diario/(?P<fecha1>[-\w]+)/(?P<fecha2>[-\w]+)/(?P<tipo>[-\w]+)/$',
        viewsets.RankinMagazineSet.as_view({'get': 'list'}),
        name='reportes-magazine'
    ),
    url(
        r'^api/reportes/canillas/lista/(?P<pk>[-\w]+)/$',
        viewsets.RankingVendorSet.as_view({'get': 'list'}),
        name='reportes-canillas'
    ),
    url(
        r'^api/reportes/canillas/historial/$',
        viewsets.HistoriaVenderSet.as_view({'get': 'list'}),
        name='reportes-historial'
    ),
    url(
        r'^api/reportes/canilla/cero/(?P<pk>[-\w]+)/$',
        viewsets.CeroVenderSet.as_view({'get': 'list'}),
        name='reportes-cero'
    ),
    url(
        r'^api/reportes/guia/lista/(?P<numero>[-\w]+)/$',
        viewsets.HistoryGuideViewset.as_view({'get': 'list'}),
        name='reportes-guia'
    ),
    url(
        r'^api/reportes/detalle-guia/(?P<pk>[-\w]+)/$',
        viewsets.DetailHistoryGuideViewset.as_view({'get': 'list'}),
        name='reportes-guia_detalle'
    ),
    url(
        r'^api/reportes/estado-guia/(?P<date1>[-\w]+)/(?P<date2>[-\w]+)/$',
        viewsets.StateGuideViewset.as_view({'get': 'list'}),
        name='reportes-guia_estado'
    ),
    url(
        r'^api/reportes/resumen-guia/(?P<date1>[-\w]+)/(?P<date2>[-\w]+)/$',
        viewsets.ResumenReportGuideViewset.as_view({'get': 'list'}),
        name='reportes-guia_resumen'
    ),
    url(
        r'^api/reporte/guia/count-real/save/$',
        viewsets.RegisterRealCountViewSet.as_view({'post': 'create'}),
        name='reporte-guia_real_count'
    ),
    #urls para vistas
    url(
        r'^reportes/ventas/neta/$',
        views.VentaNetaView.as_view(),
        name='ventas-neta'
    ),
    url(
        r'^reportes/ventas/margen-ganacia/$',
        views.MargenView.as_view(),
        name='ventas-margen'
    ),
    url(
        r'^reportes/cierre/add/$',
        views.CierreCreateView.as_view(),
        name='cierre-add'
    ),
    url(
        r'^reportes/cierre/list/$',
        views.CierreMesListView.as_view(),
        name='cierre-list'
    ),
    url(
        r'^reportes/cierre/delete/(?P<pk>\d+)/$',
        views.CierreMesDeleteView.as_view(),
        name='cierre-delete'
    ),
    url(
        r'^reportes/diarios/report/$',
        views.DiariosReport.as_view(),
        name='diarios-report'
    ),
    url(
        r'^reportes/productos/report/$',
        views.ProductReport.as_view(),
        name='product-report'
    ),
    url(
        r'^reportes/vendedores/report/$',
        views.VendorReport.as_view(),
        name='vendor-report'
    ),
    url(
        r'^reportes/vendedores/tope/$',
        views.VendorTopeReport.as_view(),
        name='vendor-tope'
    ),
    url(
        r'^reportes/vendedores/historial/$',
        views.VendorHistoriaReport.as_view(),
        name='vendor-historial'
    ),
    url(
        r'^reportes/vendedores/canilla-cero/$',
        views.VendorCeroReport.as_view(),
        name='vendor-cero'
    ),
    url(
        r'^reportes/almacen/missing$',
        views.MagazineMissingReport.as_view(),
        name='almacen-missing'
    ),
    url(
        r'^reportes/control/guias-culminadas$',
        views.ControlGuidesReport.as_view(),
        name='control-guias'
    ),
    url(
        r'^reportes/guias-panel$',
        views.GuidesReport.as_view(),
        name='reporte-guias'
    ),
    url(
        r'^reportes/guias-items/(?P<pk>\d+)/$',
        views.GuidesItemReport.as_view(),
        name='reporte-guias_item'
    ),
    url(
        r'^reportes/guias-items-detalle/(?P<pk>\d+)/$',
        views.GuidesItemDetalleReport.as_view(),
        name='reporte-guias_item_detalle'
    ),
    url(
        r'^reportes/guias-estado/$',
        views.GuideEstadoReport.as_view(),
        name='reporte-guias_estado'
    ),
    url(
        r'^reportes/guias-resumen/$',
        views.GuideResumenReport.as_view(),
        name='reporte-guias_resumen'
    ),
]

swnpuerto/nmagazine/nmagazine/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib import admin
#import debug_toolbar

urlpatterns = [
    url(r'^', include('applications.users.urls', namespace="users_app")),
    url(r'^', include('applications.almacen.entidad.urls', namespace="entidad_app")),
    url(r'^', include('applications.almacen.recepcion.urls', namespace="recepcion_app")),
    url(r'^', include('applications.almacen.kardex.urls', namespace="kardex_app")),
    url(r'^', include('applications.almacen.asignacion.urls', namespace="asignacion_app")),
    url(r'^', include('applications.almacen.devolucion.urls', namespace="devolucion_app")),
    url(r'^', include('applications.caja.pagos.urls', namespace="pagos_app")),
    url(r'^', include('applications.caja.liquidacion.urls', namespace="liquidacion_app")),
    url(r'^', include('applications.reportes.urls', namespace="reportes_app")),
    url(r'^', include('applications.administrador.urls', namespace="administrador_app")),
    url(r'^', include('applications.control.urls', namespace="control_app")),

    url(r'^admin/', admin.site.urls),
    #url(r'^__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swnpuerto/nmagazine/applications/reportes/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from .models import CierreMes


class CierreForm(forms.ModelForm):

    class Meta:
        model = CierreMes
        fields = (
            'mes',
            'date_start',
            'date_end',
            'venta_neta_real',
            'ingreso_neto_real',
        )
        widgets = {
            'mes':forms.Select(
                attrs={
                    'class': 'form-control input-sm'
                }
            ),
            'date_start': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'id':'datetimepicker1',
                    'type':'date',
                    'ng-model':'vm.fecha1',
                    'ata-date-format':'DD-MM-YYYY',
                },
            ),
            'date_end': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'id':'datetimepicker1',
                    'type':'date',
                    'ng-model':'vm.fecha2',
                    'ata-date-format':'DD-MM-YYYY',
                    'ng-change':'vm.consulta_montos(vm.fecha1,vm.fecha2)'
                },
            ),
            'venta_neta_real': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'ng-model':'vm.venta_real'
                }
            ),
            'ingreso_neto_real': forms.TextInput(
                attrs={
                    'class': 'form-control input-sm',
                    'ng-model':'vm.ingreso_real'
                }
            ),
        }

    def clean_venta_neta_real(self):
        venta_neta_real = self.cleaned_data['venta_neta_real']
        if venta_neta_real < 0:
            raise forms.ValidationError("Ingrese monto valido")

        return venta_neta_real

    def clean_ingreso_neto_real(self):
        ingreso_neto_real = self.cleaned_data['ingreso_neto_real']
        if ingreso_neto_real < 0:
            raise forms.ValidationError("Ingrese monto valido")

        return ingreso_neto_real

    def clean_date_end(self):
        date_start = self.cleaned_data['date_start']
        date_end = self.cleaned_data['date_end']
        if date_end < date_start:
            raise forms.ValidationError("Ingrese fecha valida")

        return date_end

swnpuerto/nmagazine/applications/reportes/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import redirect
from datetime import datetime
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView,
    ListView,
    DeleteView,
    CreateView,
    DetailView,
)

from applications.caja.liquidacion.functions import liquidacion_guia_detalle

from .models import CierreMes
from applications.almacen.recepcion.models import Guide, DetailGuide
from applications.caja.pagos.models import Payment

from .forms import CierreForm

class VentaNetaView(TemplateView):
    template_name = 'reportes/ventas/neta.html'


class MargenView(TemplateView):
    template_name = 'reportes/ventas/margen.html'


class CierreCreateView(CreateView):
    """vista que registra cierre de un mes"""
    form_class = CierreForm
    success_url = reverse_lazy('reportes_app:cierre-list')
    template_name = 'reportes/cierre/add.html'

    def form_valid(self, form):
        cierre = form.save(commit=False)
        cierre.user_created = self.request.user
        cierre.user_modified = self.request.user
        dt1 = form.cleaned_data['date_start']
        dt2 = form.cleaned_data['date_end']
        fecha1 = str(dt1.strftime('%d-%m-%Y'))
        fecha2 = str(dt2.strftime('%d-%m-%Y'))
        consulta = liquidacion_guia_detalle(fecha1,fecha2)

        #calculamos ingreso neto real, venta neta real
        ingre_neto = 0
        venta_neta = 0
        #iteramos consulta
        for c in consulta:
            suma_ingres = 0
            suma_venta = 0
            for d in c.detalle:
                suma_ingres = suma_ingres + d.vendido*d.precio_guia
                suma_venta = suma_venta + d.vendido*d.precio_venta
            ingre_neto = ingre_neto + suma_ingres
            venta_neta = venta_neta + suma_venta
        #guardamos los valores

        cierre.venta_neta = venta_neta
        cierre.ingreso_neto = venta_neta - ingre_neto
        cierre.save()
        return super(CierreCreateView, self).form_valid(form)


class CierreMesListView(TemplateView):
    template_name = 'reportes/cierre/list.html'


class CierreMesDeleteView(DeleteView):
    model = CierreMes
    success_url = reverse_lazy('reportes_app:cierre-list')
    template_name = 'reportes/cierre/delete.html'


class DiariosReport(TemplateView):
    template_name = 'reportes/diarios/report.html'


class ProductReport(TemplateView):
    template_name = 'reportes/productos/report.html'


class VendorReport(TemplateView):
    template_name = 'reportes/canillas/report.html'


class VendorTopeReport(TemplateView):
    template_name = 'reportes/canillas/tope.html'


class VendorHistoriaReport(TemplateView):
    template_name = 'reportes/canillas/historial.html'


class VendorCeroReport(TemplateView):
    template_name = 'reportes/canillas/cero.html'


class MagazineMissingReport(TemplateView):
    template_name = 'reportes/almacen/perdidas.html'


class ControlGuidesReport(TemplateView):
    template_name = 'admin/control/guides_culmined.html'


class GuidesReport(TemplateView):
    template_name = 'reportes/almacen/reporte_guias.html'


class GuidesItemReport(DetailView):
    model = Guide
    template_name = 'reportes/almacen/items_guias.html'


class GuidesItemDetalleReport(DetailView):
    model = DetailGuide
    template_name = 'reportes/almacen/items_detalle.html'

    def get_context_data(self, **kwargs):
        context = super(GuidesItemDetalleReport, self).get_context_data(**kwargs)
        context['deudas'] = Payment.objects.deuda_magazine_vendor(
            self.get_object().pk,
        )
        return context


class GuideEstadoReport(TemplateView):
    template_name = 'reportes/almacen/estado_guias.html'


class GuideResumenReport(TemplateView):
    template_name = 'reportes/almacen/resumen_guias.html'

swnpuerto/nmagazine/templates/caja/cobros/reportes/anulados.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Ultimas Devoluciones {% endblock title %}


{% block main %}
<h2 class="col-sm-offset-2 page-title">Boletas Anuladas Durante el Dia</h2>
<div class="row">
  <div class="col-md-12">
      <section class="widget widget-chart-stats-simple">
          <div class="widget-body">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <td>
                      Canilla
                    </td>
                    <td>
                      Boleta
                    </td>
                    <td>
                      Hora
                    </td>
                    <td>
                      Detalle
                    </td>
                  </tr>
                </thead>

                <tbody>
                  {% for l in list_invoce  %}
                  <tr>
                    <td><span class="text-primary"><strong>{{l.vendor}}</strong></span></td>
                    <td>{{l.pk}}</td>
                    <td>{{l.created}}</td>
                    <td>
                      <a href="{% url 'pagos_app:pagos-anulado-detalle' l.pk %}" class="btn btn-success"><i class="fa fa-search"></i></a>
                    </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
      </section>
  </div>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/detalle_anulados.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Detalle Boleta Anulada {% endblock title %}


{% block main %}
<h1 class="page-title">Pagos de Boleta Anulada</h1>
<div class="col-md-12">
    <section class="widget">
        <header>

            <div class="widget-controls">
                <a href="#"><i class="fa fa-refresh"></i></a>
            </div>
        </header>
        <div class="widget-body">
          <div class="alert alert-success" role="alert">
            <span class="fw-semi-bold">{{boleta}}</span>
          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Boleta</th>
                  <th>Canilla</th>
                  <th>diario</th>
                  <th>Monto</th>
                  <th>Hora</th>
                </tr>
              </thead>
              <tbody>
                {% for l in  list_payment %}
                  <tr>
                      <td>{{l.invoce.pk}}</td>
                      <td>{{l.invoce.vendor}}</td>
                      <td>{{l.count_payment}}</td>
                      <td>S./{{l.amount}}</td>
                      <td>{{l.created}}</td>
                      {% empty %}
                          <td colspan="7">No se Registro Pagos El Dia de Hoy</td>
                  </tr>
                  {% endfor %}
              </tbody>
            </table>
            <div class="col-sm-offset-4 col-md-4">
              <a href="{% url 'pagos_app:pagos-anulados' %}" type="button" class="btn btn-default btn-block">Volver</i></a>
            </div>
          </div>
        </div>
    </section>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/detalle_devolucion.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Detalle Movimientos {% endblock title %}


{% block main %}
<h1 class="page-title">Movimientos Diarios Devuletos</h1>
<div class="col-md-12">
    <section class="widget">
        <header>

            <div class="widget-controls">
                <a href="#"><i class="fa fa-refresh"></i></a>
            </div>
        </header>
        <div class="widget-body">
          <div class="alert alert-success" role="alert">
            <span class="fw-semi-bold">{{magazine}}</span>
          </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Reg.</th>
                  <th>Boleta</th>
                  <th>Canilla</th>
                  <th>Catntidad</th>
                  <th>Hora</th>
                </tr>
              </thead>
              <tbody>
                {% for l in  list_vendor %}

                    <tr>
                      {% if l.count_return > 0 %}
                        <td>{{l.payment.pk}}</td>
                        <td>{{l.payment.invoce.pk}}</td>
                        <td>{{l.payment.invoce.vendor}}</td>
                        <td><span class="text-primary"><strong>{{l.count_return}}</strong></span></td>
                        <td>{{l.payment.created}}</td>
                      {% endif %}
                      {% empty %}
                          <td colspan="7">No se Registro Pagos El Dia de Hoy</td>
                    </tr>
                  {% endfor %}
              </tbody>
            </table>
            <div class="col-sm-offset-4 col-md-4">
              <a href="{% url 'pagos_app:pagos-devoluciones' %}" type="button" class="btn btn-default btn-block">Volver</i></a>
            </div>

          </div>
        </div>
    </section>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/devoluciones.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Devolucion Caja {% endblock title %}


{% block main %}
<div ng-app="MagazineApp" ng-controller="LiquidacionDiaCtrl as vm" ng-init="vm.liquidacion_por_dia(fecha)">
  <div class="row">
    <div class="col-md-12">
        <section class="widget bg-success text-white">
            <div class="widget-body">
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                      <h2 class="text-center">
                        <span class="center"><strong>Total Devuelto: <strong> {$ vm.total_devuelto $}</strong></span>
                      </h2>
                    </div>
                </div>
            </div>
        </section>
    </div>
  </div>
  <div class="panel panel-default">
    <div id="print-section">
      <section class="widget">
        <div class="row">
          <h3 class="text-center"><strong><u>Lista de Movimientos Devoluciones</u></strong></h3>
          <h5 class="text-center">Fecha: {$ vm.date|date $}</h5>
        </div>
      <div class="row">
        <legend></legend>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Item</th>
              <th>Fecha</th>
              <th>Cantidad</th>
            </tr>
          </thead>
          <tbody ng-repeat="l in vm.liquidacion">
            <tr ng-if="!vm.venta_caja(l.name)" ng-repeat="i in l.lista_pagos">
              <td>{$ i.magazine $}-{$ i.dia $}</td>
              <td>{$ i.date $}</td>
              <td> {$ i.devuelto $}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <legend></legend>
      <div class="row center">
        <h4 class="text-center">Control:........................... &nbsp; &nbsp; &nbsp; &nbsp; Caja: ...........................</h4>
        <legend></legend>
      </div>
      </section>
    </div>
  </div>
    <div class="row">
      <div class="col-md-12">
          <section class="widget">
              <div class="form-actions">
                  <div class="row">
                      <div class="col-sm-offset-5 col-sm-7">
                        <button ng-click="vm.imprimir()" class="btn btn-primary">Imprimir</a>
                      </div>
                  </div>
              </div>
          </section>
      </div>
    </div>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/export_devolucion.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Liquidacion {% endblock title %}


{% block main %}
<div ng-app="MagazineApp" ng-controller="DevolucionCtrl as vm" ng-init="vm.cargar_devolucion_caja()">

<h3> <toast></toast></h3>
<div class="col-md-12">
  <section class="widget">
        <h3 class="text-primary text-center"><strong>Detalle Devoluciones</strong></h3>
  </section>

  <section class="widget">
       <div id="grid1" ui-grid="vm.gridOptions" ui-grid-edit ui-grid-cellnav ui-grid-exporter class="grid"></div>
  </section>
    <section class="widget">
      <button class="btn btn-sm btn-warning" ng-click="vm.exportar_pdf()">PDF</button>
      <button class="btn btn-sm btn-success" ng-click="vm.exportarExcel()">Excel</button>
    </section>

</div>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/faltantes.html
{% extends "base/dashboardCaja.html" %}

{% block title %} Cuadrar Caja {% endblock title %}


{% block main %}
<div class="row">

  <legend>Lista de Vendedores Faltantes hoy</legend>
  {% for l in list_vendors  %}
  <div class="col-md-12 widget-container">
      <section class="widget" id="news-widget" data-widgster-load="demo/ajax/widgets/news.php">
          <header>
              <h3>
                  {{l.cod}}-{{l.name}} <span class="badge bg-success">Dni:{{l.dni}}</span>
              </h3>
              <span class="text-primary">Seudonimo:{{l.seudonimo}}</span>
              <div class="widget-controls">
                  <a data-widgster="load" title="Notificar" href="#"><i class="fa fa-refresh"></i></a>
              </div>
          </header>
      </section>
  </div>
  {% endfor %}
</div>

{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/guias_pendientes.html
{% extends "base/dashboardCaja.html" %}

{% block title %}Guias Pendientes{% endblock title %}

{% block main %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 style="text-align:center;">Lista de guias no cerradas</h3>
  </div>
</div>

<div class="panel panel-default">
  <div id="print-section">
    <section class="widget">
      <div class="row">
        <legend></legend>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Guia</th>
              <th>Fecha</th>
              <th>Proveedor</th>
              <th>estado</th>
              <th>Accion</th>
            </tr>
          </thead>
          <tbody>
            {% for g in guias  %}
              <tr>
                <td>{{g.number}}</td>
                <td>{{g.created}}</td>
                <td>{{g.provider}}</td>
                <td><a href="{% url 'pagos_app:guias-pendientes-detalle' g.pk %}" class="btn btn-success"><i class="fa fa-sign-out"></i>Ver</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <legend></legend>
        <legend></legend>
      </div>
    </section>
  </div>
</div>
{% endblock main %}

swnpuerto/nmagazine/templates/caja/cobros/reportes/vendors_deudas.html
{% extends "base/dashboardCaja.html" %}

{% block title %}Guias Pendientes - deudores{% endblock title %}

{% block main %}
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 style="text-align:center;">Items por cobrar para guia: <b> {{guia}} </b></h3>
  </div>
</div>

<div class="panel panel-default">
  <div id="print-section">
    <section class="widget">
      <div class="row">
        <legend></legend>
        <table class="table table-condensed">
          <thead>
            <tr>
              <th>Codigo</th>
              <th>Canilla</th>
              <th>Fecha. Entr</th>
              <th>Item</th>
              <th>Deuda</th>
            </tr>
          </thead>
          <tbody>
            {% for v in vendors  %}
              <tr>
                <td>{{v.cod}}</td>
                <td>{{v.vendor}}</td>
                <td>{{v.date}}</td>
                <td>{{v.magazine}}</td>
                <td>{{v.deuda}}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <legend></legend>
        <legend></legend>
      </div>
    </section>
  </div>
</div>
{% endblock main %}